### ISSUE TITLE
Please write to the README/main page: why do we need this project if we already have the MDN?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [iliakan/javascript-tutorial-en#340]

**Comment by davegregg** [comment]
This tutorial is 1) more concise, 2) easier to navigate, 3) more guided, 4) is more opinionated about best-practices, 5) has executable code blocks, 6) has Tasks (and Demos).

**Comment by iliakan** [comment]
MDN is *not* a tutorial. It has some tutorials, but we love it for being a *manual*, which is a pretty different thing.

**Comment by vitaly-zdanevich** [comment]
Your project looks nice, good UI, but MDN sometimes has a runnable code too through embedded Codepen or by using internal mechanism. Just my thoughts - maybe for the community will be better to target our effort to the one place? We can improve MDN with tutorial and best practice too.

**Comment by iliakan** [comment]
That would be wrong, because different people like different things. Someone finds it easier to understand my explanation. Another person would prefer another approach. The third one would ditch them all and looks for smth else. 

Just as people are different, learning resources should be different. Let thousand different flowers grow not a single one.

**Comment by davegregg** [comment]
We also can't discount the value of being able to read different explanations for the same thing. I know sometimes my students struggle to understand the MDN documentation, so we are currently recommending two resources for our JavaScript newbies: MDN and JavaScript.info.
