### ISSUE TITLE
problem in mobile view

### ISSUE THREAD

**Issue by golarajahangir** [iliakan/javascript-tutorial-en#48]
the java script fundamental's items in the desktop view are not exactly the same as the items in the mobile view

**Comment by OmelDM** [comment]
Hello. I hope I can help with addressing this issue. There are 'More...' buttons and some hidden list items on small screens: 
![screen shot 2017-06-22 at 10 01 14 am](https://user-images.githubusercontent.com/8970873/27421228-2f5aaa68-5732-11e7-8f0e-3d0cf831e2ec.png)

After clicking 'More...' buttons not all list items are showed (there should be 16 items instead of 11): 
![screen shot 2017-06-22 at 10 04 54 am](https://user-images.githubusercontent.com/8970873/27421272-60beabf4-5732-11e7-8818-a2f9d3e54c71.png)

There is a small issue in 'More...' button click event handler – live HTMLCollection is changing during for-loop, every iteration the length of hiddenBlock is decreasing: 
![screen shot 2017-06-22 at 9 54 02 am](https://user-images.githubusercontent.com/8970873/27421461-31526bb6-5733-11e7-91d8-4a573262172e.png)

One of solutions is reverse iteration through hiddenBlock collection:
![screen shot 2017-06-22 at 10 15 26 am](https://user-images.githubusercontent.com/8970873/27421675-1f063a22-5734-11e7-8167-94936184c445.png)

Unfortunately I couldn't find source code on this repository to prepare pull request to fix the issue.

**Comment by iliakan** [comment]
Hopefully fixed.
