### ISSUE TITLE
01-02-01 Hello, World! article.md file doesn't appear to be synced with the website

### ISSUE THREAD

**Issue by imidom** [iliakan/javascript-tutorial-en#652]
The [01-02-01 Hello, World! article.md](https://github.com/iliakan/javascript-tutorial-en/blob/master/1-js/02-first-steps/01-hello-world/article.md) file looks like it's outdated. There are a bunch of formatting issues not present on the [live webpage's version of the page](https://javascript.info/hello-world). Can we update the article.md file in GitHub with the current version that's online?

**Comment by imidom** [comment]
Hi @iliakan, any word on updating the files here to match the website?

**Comment by iliakan** [comment]
You say, the living version is more up to date than the version in the repository?

**Comment by imidom** [comment]
Yes, I think so. The repository version has issues that the living version doesn't. 

For instance, the **Modern Markup** section of the repository looks like this:
![image](https://user-images.githubusercontent.com/8891864/50012426-98458f80-ff8c-11e8-9ad1-bb49afb9863b.png)
Whereas the living version looks much better:
![image](https://user-images.githubusercontent.com/8891864/50012438-a5627e80-ff8c-11e8-9855-1f2ba796435f.png)
We could make a lot of progress if the repository version matched the living one.

Thanks!

**Comment by iliakan** [comment]
Ah, I got it now.

The reason is that the markup used on-site is a little bit more advanced than the one used by github. In other words, it has some specific stuff like runnable code fragments etc.

That's why the website shows it differently.

But fear not, there's a tutorial server https://github.com/iliakan/javascript-tutorial-server, it allows to run the tutorial locally (on your computer), browse it and (!) see how the changes look immediately when you add them to the text ;)
